### ISSUE TITLE
Bio.Alphabet error in the script getAnnoFastaFromJoingenes.py

### ISSUE THREAD

**Issue by gsilvaarias** [Gaius-Augustus/BRAKER#274]
Hello,

I got an error in braker during annotation process. Here my command:
```bash
braker.pl --species=S_chilense \
	--genome=S_new_TEsoftmasked.fasta \
	--bam=RNA1.sorted.bam,RNA2.sorted.bam,RNA3.sorted.bam,RNA4.sorted.bam,RNAt3.sorted.bam,RNAt9.sorted.bam \
	--GENEMARK_PATH=gmes_linux_64 \
	--softmasking \
	--cores 48 \
	--workingdir=braker_outfiles
```

Here the error mesage in the log file:
```
ERROR in file braker.pl at line 9664
Failed to execute: python3 getAnnoFastaFromJoingenes.py -g braker_outfiles/genome.fa -f braker_outfiles/augustus.hints.gtf -o braker_outfiles/augustus.hints 1> braker_outfiles/getAnnoFastaFromJoingenes.augustus.hints_tmp.stdout 2>braker_outfiles/errors/getAnnoFastaFromJoingenes.augustus.hints_tmp.stderr
```
Here the content of the file `getAnnoFastaFromJoingenes.augustus.hints_tmp.stderr` :
```python
Traceback (most recent call last):
  File "Augustus/scripts/getAnnoFastaFromJoingenes.py", line 35, in <module>
    from Bio.Alphabet import generic_dna, generic_protein
  File ".conda/envs/braker/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".conda/envs/braker/bin/getAnnoFastaFromJoingenes.py", line 39, in <module>
    raise ImportError(
ImportError: Failed to import biophython modules. Try installing with "pip3 install biopython"
```

I appreciate any support to solve this problem.

Best,
Gustavo

**Comment by tomasbruna** [comment]
Hello Gustavo,

please try the solution proposed in https://github.com/Gaius-Augustus/Augustus/issues/200.

Best,
Tomas

**Comment by gsilvaarias** [comment]
Hi Tomas,
thanks for the reply. That solution works well.
Just removing **Bio.Alphabet** `generic_dna` calls from the script fix the problem.

Best,
Gustavo

**Comment by KatharinaHoff** [comment]
Thanks for reporting. I have fixed it with https://github.com/Gaius-Augustus/Augustus/commit/34a3ce32cbe48b279fe5e0cff3b3bf113a0d2e9b

Best,

Katharina
