### ISSUE TITLE
Issue in fix_in_frame_stop_codon_genes.py

### ISSUE THREAD

**Issue by jeankeller** [Gaius-Augustus/BRAKER#592]
Hello,

I am trying to use BRAKER3 but it fails at the fix_in_frame_stop_codon_genes.py step. I've tried with and without RNASeq data, same error each time. 
command line that failed:
`ERROR in file /opt/BRAKER/scripts/braker.pl at line 7031
Failed to execute: /usr/bin/python3 /usr/share/augustus/scripts/fix_in_frame_stop_codon_genes.py -g /home/jkeller/annotation_lagvil/braker/genome.fa -t /home/jkeller/annotation_lagvil/braker/augustus.hints.gtf -b /home/jkeller/annotation_lagvil/braker/bad_genes.lst -o augustus.hints_fix_ifs_ -s Lagvil -m on --UTR off --print_utr off -a /home/jkeller/.augustus -C /opt/cdbfasta -A /usr/bin/ -S /usr/share/augustus/scripts/ -H /home/jkeller/annotation_lagvil/braker/hintsfile.gff -e /opt/BRAKER/scripts/cfg/etp.cfg  > /home/jkeller/annotation_lagvil/braker/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /home/jkeller/annotation_lagvil/braker/errors/fix_in_frame_stop_codon_genes_augustus.hints.err`

Traceback from fix_in_frame_stop_codon_genes_augustus.hints.err

> Traceback (most recent call last):
  File "/usr/share/augustus/scripts/fix_in_frame_stop_codon_genes.py", line 701, in <module>
    with multiprocessing.Pool(processes = args.cores) as pool:
  File "/usr/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 346, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/usr/lib/python3.10/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 341, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.10/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory

BRAKER version: 3.0.2

I am using the Singularity container.

Would you have any idea of what's going on? 

Thank you

**Comment by jeankeller** [comment]
I've also tried to set up different PYTHON3_PATH (to not take the conda) and to reinstall singularity and build a BRAKER in a fresh environment without conda installed. Didn't solved the problem

**Comment by ItokawaK** [comment]
I have gotten exactly same error today. 

Environment: Ubuntu 20.04 in WSL2
Version: 3.0.6 in singularity container

test1.sh also failed in same manner.

Interestingly, it worked fine in anaother machine with non WSL2 ubuntu 20.04.

I am not sure, but it could be a problem on WSL2(?)

**Comment by jeankeller** [comment]
Got the same error only on WSL2. I tried with fresh installation of WSL2 running Ubuntu-22.04/Ubuntu-20.04 and still got the error.

**Comment by KatharinaHoff** [comment]
There‘s a way to suppress that the container sees the outside stuff. Clean
env option. I am on my phone and can’t check on details.

Jean Keller ***@***.***> schrieb am Do. 11. Jan. 2024 um
13:53:

**Comment by ItokawaK** [comment]
Hi @jeankeller 

Are you still having this problem?
I might have found a good workaround.

Try use `--contain` option like below.

```
singularity exec -H $PWD  --contain braker3.sif braker.pl --genome=/opt/BRAKER/example/genome.fa --bam=/opt/BRAKER/example/RNAseq.bam --softmasking --workingdir=test1 --threads 8 --gm_max_intergenic 10000 --skipOptimize
```

It worked in my WSL2 environment.

Thanks to this issue comment.
https://github.com/marcelm/cutadapt/issues/583#issuecomment-988629221
