### ISSUE TITLE
gc_content.stderr!

### ISSUE THREAD

**Issue by sowmiyakathir** [Gaius-Augustus/BRAKER#669]
I got this error while running BRAKER. It throws an error like this while estimating the GC content in our input data. Please help me with this.
Many thanks for considering my request. 

Comment:
nohup /home/tools/BRAKER/scripts/braker.pl --genome=./LM.scafSeq.masked --prot_seq=/home/data/Plant_nt.fna --AUGUSTUS_CONFIG_PATH=/home/tools/Augustus/config/ --AUGUSTUS_BIN_PATH=/home/tools/Augustus/bin/ --AUGUSTUS_SCRIPTS_PATH=/home/tools/Augustus/scripts/ --GENEMARK_PATH=/home/Tools/gmes_linux_64_4/ --PROTHINT_PATH=/home/tools/ProtHint/bin/ --TSEBRA_PATH=/home/tools/TSEBRA/bin/ --threads=18 --gff3

#####################################################################################################
Fri Sep  : Log information is stored in file /home/data/braker/braker.log
ERROR in file /home/tools/BRAKER/scripts/braker.pl at line 5826
failed to execute: /home/tools/BRAKER/scripts/get_gc_content.py --sequences /home/data/LM.scafSeq.masked --print_sequence_length 1> /home/data/braker/gc_content.out 2> /home/data/braker/errors/gc_content.stderr!

# **braker.log**
Fri Sep  : getting GC content of the genome
/home/tools/BRAKER/scripts/get_gc_content.py --sequences /home/data/LM.scafSeq.masked --print_sequence_length 1> /home/data/braker/gc_content.out 2> /home/data/braker/errors/gc_content.stderr

# **gc_content.stderr**
Traceback (most recent call last):
  File "/home/tools/BRAKER/scripts/get_gc_content.py", line 217, in <module>
    main()
  File "/home/tools/BRAKER/scripts/get_gc_content.py", line 88, in main
    print_gc_range(gc_content)
  File "/home/tools/BRAKER/scripts/get_gc_content.py", line 138, in print_gc_range
    gc_range.append(get_percentile(all_slices, p))
  File "/home/tools/BRAKER/scripts/get_gc_content.py", line 143, in get_percentile
    return np.percentile(array, q)
  File "<__array_function__ internals>", line 180, in percentile
  File "/home/miniconda3/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4166, in percentile
    return _quantile_unchecked(
  File "/home/miniconda3/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4424, in _quantile_unchecked
    r, k = _ureduce(a,
  File "/home/miniconda3/lib/python3.10/site-packages/numpy/lib/function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "/home/miniconda3/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4593, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/home/miniconda3/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4699, in _quantile
    take(arr, indices=-1, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 180, in take
  File "/home/miniconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/miniconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

**Comment by KatharinaHoff** [comment]
@LarsGab do you have any idea what's going on here?

**Comment by LarsGab** [comment]
Hi, 

it looks likethat the script isn't detecting the sequences from your genome fasta file (` /home/data/LM.scafSeq.masked`). Are the sequences in the file in FASTA format and not empty?

Best, Lars

**Comment by sowmiyakathir** [comment]
Hi @LarsGab ,

Yes, the sequence in the file is in FASTA format and it's not empty.

**Comment by sowmiyakathir** [comment]
@LarsGab ,
Could you reply to me? I am still waiting for a solution.

**Comment by KatharinaHoff** [comment]
I have not pushed a docker update or release, yet. The change is only on
GitHub.

Lars Gabriel ***@***.***> schrieb am Di. 14. Nov. 2023 um
13:57:

**Comment by KatharinaHoff** [comment]
Now we have a new release and Docker container is also updated.

**Comment by sowmiyakathir** [comment]
Hi @LarsGab,
Thanks for the reply, I will try the new update and let you know if I still get an issue.  And of course, I will share my genome file if I get an issue again.

**Comment by KatharinaHoff** [comment]
I hope you did not experience the problem, again. I am closing here. Feel free to re-open if the problem persists.
