### ISSUE TITLE
fix_in_frame_stop_codon_genes.py crashes on line 701

### ISSUE THREAD

**Issue by rainmanv84** [Gaius-Augustus/BRAKER#873]
Running BRAKER 3.0.8 on Ubuntu-20.04 (WSL2) in Singularity-CE-4.2.1

On some genomes the pipeline crashes:

braker.log:
`/opt/conda/bin/python3 /opt/Augustus/scripts/fix_in_frame_stop_codon_genes.py -g /home/rainman/Work/Gene_annotation/wd/GCA_001051215.1_ASM105121v1_genomic.fna/genome.fa -t /home/rainman/Work/Gene_annotation/wd/GCA_001051215.1_ASM105121v1_genomic.fna/augustus.hints.gtf -b /home/rainman/Work/Gene_annotation/wd/GCA_001051215.1_ASM105121v1_genomic.fna/bad_genes.lst -o augustus.hints_fix_ifs_ -s GCA_001051215.1_ASM105121v1_genomic.fna -m on --UTR off --print_utr off -a /home/rainman/Work/Gene_annotation/wd/GCA_001051215.1_ASM105121v1_genomic.fna/config -C /opt/cdbfasta -A /opt/Augustus/bin/ -S /opt/Augustus/scripts/ -H /home/rainman/Work/Gene_annotation/wd/GCA_001051215.1_ASM105121v1_genomic.fna/hintsfile.gff -e /opt/BRAKER/scripts/cfg/ep.cfg  > /home/rainman/Work/Gene_annotation/wd/GCA_001051215.1_ASM105121v1_genomic.fna/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /home/rainman/Work/Gene_annotation/wd/GCA_001051215.1_ASM105121v1_genomic.fna/errors/fix_in_frame_stop_codon_genes_augustus.hints.err`

fix_IFS_log_: no errors

fix_in_frame_stop_codon_genes_augustus.hints.err:
`Traceback (most recent call last):
  File "/opt/Augustus/scripts/fix_in_frame_stop_codon_genes.py", line 701, in <module>
    with multiprocessing.Pool(processes = args.cores) as pool:
  File "/opt/conda/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 346, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/opt/conda/lib/python3.10/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 341, in __init__
    self._rlock = ctx.Lock()
  File "/opt/conda/lib/python3.10/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/opt/conda/lib/python3.10/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/opt/conda/lib/python3.10/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory`

Solution (at least for me):
`export TMPPATH=/tmp/`

**Comment by rainmanv84** [comment]
Oops, the above mentioned solution did not resolve the situation completely.
Crashes got somewhat more rare, but still present at the same place
