### ISSUE TITLE
best_bycomleasm.py ERROR (GeneMark trancript too long)

### ISSUE THREAD

**Issue by jolbi** [Gaius-Augustus/BRAKER#882]
Hi,

I am running BRAKER3 in ETP mode in singularity container (braker.pl  v3.0.8). I am running it on four haplotypes of one assembly separately.
The run was successful for 3 haplotypes, but for one it stops with an error in compleasm step.
I don't understand completely the steps here, but one thing I noticed is that all files in bbc/genemark/solanales_odb10_hmmsearch_output/*.out are empty.
I then tried to run the compleasm.py command again, and I get 5000+ errors like this:
´´´
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
´´´
Which comes from hmmsearch that is run as part of compleasm.
I checked the genemark.aa and genemark.gtf and there is indeed one abnormal gene whose amino acid sequence exeeds 100k length limit of hmmsearch.

**What can I do about it?**
Is there an option to resume the pipeline after I remove it manually?
I understand that this is almost the last step of the BRAKER pipeline. Could I manually run the rest of it?
Or even better, **are there some parameters that can be set for GeneMark-ETP**, so it does not produce abnormal transcripts (like this one with 5000+ exons)? Like some limits for number of introns / lengths etc.?

It could be there are some assembly errors or other problems in that genomic region. I am looking into that.

I am attaching the logs, if someone else searches for the braker/compleasm errors.
braker.log (last lines):
```
# Thu Oct 31 11:57:08 2024: Making a fasta file with protein sequences of /XXX/augustus.hints.gtf
/opt/conda/bin/python3 /opt/Augustus/scripts/getAnnoFastaFromJoingenes.py -g /XXX/genome.fa -f /XXX/augustus.hints.gtf -o /XXX/augustus.hints 1> /XXX/getAnnoFastaFromJoingenes.augustus.hints_hints.stdout 2>/XXX/errors/getAnnoFastaFromJoingenes.augustus.hints_hints.stderr
# Thu Oct 31 11:57:32 2024: AUGUSTUS prediction complete
# Thu Oct 31 11:57:32 2024: Trying to create merged gene set from GeneMark-EX and AUGUSTUS predictions (braker.gtf/braker.utr.gtf)...
# Thu Oct 31 11:57:32 2024: Trying to create combined gene set with TSEBRA...
/opt/TSEBRA/bin/tsebra.py --gtf /XXX/augustus.hints.gtf,/XXX/GeneMark-ETP/genemark.gtf --keep_gtf /XXX/GeneMark-ETP/training.gtf --hintfiles /XXX/hintsfile.gff --filter_single_exon_genes --cfg /opt/TSEBRA/bin/../config/braker3.cfg --out /XXX/braker.gtf -q 2>/XXX/errors/tsebra.stderr
mv /XXX/braker.gtf /XXX/braker.gtf_temp
# Thu Oct 31 12:00:06 2024: Making a fasta file with protein sequences of /XXX/braker.gtf
/opt/conda/bin/python3 /opt/Augustus/scripts/getAnnoFastaFromJoingenes.py -g /XXX/genome.fa -f /XXX/braker.gtf -o /XXX/braker 1> /XXX/getAnnoFastaFromJoingenes.braker_.stdout 2>/XXX/errors/getAnnoFastaFromJoingenes.braker_.stderr
# Thu Oct 31 12:00:23 2024: selecting best gene set by BUSCO completeness via compleasm.
# Thu Oct 31 12:00:23 2024: /opt/conda/bin/python3 /opt/TSEBRA/bin/best_by_compleasm.py -m /XXX/bbc -d /XXX -g /XXX/genome.fa -t 40 -p solanales_odb10 -y /opt/TSEBRA/bin/tsebra.py -f /opt/Augustus/scripts/getAnnoFastaFromJoingenes.py 1> /XXX/best_by_compleasm.log 2> /XXX/errors/best_by_compleasm.err
```
best_by_compleasm.log
```
/opt/Augustus/scripts/getAnnoFastaFromJoingenes.py -g /XXX/genome.fa -f /XXX/GeneMark-ETP/genemark.gtf -o /XXX/bbc/genemark -s True
/opt/compleasm_kit/compleasm.py protein -p /XXX/bbc/genemark.aa -l solanales_odb10 -t 40 -o /XXX/bbc/genemark
Error in file /opt/TSEBRA/bin/best_by_compleasm.py at line 307: Return code of subprocess was 1['/opt/compleasm_kit/compleasm.py', 'protein', '-p', '/XXX/bbc/genemark.aa', '-l', 'solanales_odb10', '-t', '40', '-o', '/XXX/bbc/genemark']
```
The version of best_by_compleasm.py is 1.0.1.

**Comment by KatharinaHoff** [comment]
Thank you for pointing out the problem of abnormally long genes. I am not sure when we will have the time to fix it, but luckily, you can finish your run.

After removing the abnormally long gene (which you already identified) from the genemark gtf file (delete the genemark.aa file, fix the gtf file), you can execute best_by_compleasm like this:

```
python3 best_by_compleasm.py -m output_folder -d braker_output_folder -g genome.fa -t nubmer_of_threads -p odb_set -y tsebra_py_location/tsebra.py -f getAnnoFastaFromJoingenes_location/getAnnoFastaFromJoingenes.py
```
This will generate the output files in the output_folder. The output_folder can be a subfolder of braker_output_folder if you want.

**Comment by KatharinaHoff** [comment]
You are welcome. Please keep this issue open. It's a bug that should be
fixed at some point in time.

**Comment by josieparis** [comment]
Hi Katharina! Hi Jolbi,

I seem to be encountering a similar issue. I'm using the singularity container for braker3. 
However, the best_by_compleasm.py error crashes on a different line:

```
/opt/Augustus/scripts/getAnnoFastaFromJoingenes.py -g xxx/kp_genome/genome.fa -f xxx/kp_genome/GeneMark-ETP/genemark.gtf -o xxx/kp_genome/bbc/genemark -s True
/opt/compleasm_kit/compleasm.py protein -p xxx/kp_genome/bbc/genemark.aa -l aves_odb10 -t 16 -o xxx/kp_genome/bbc/genemark
Error in file /opt/TSEBRA/bin/best_by_compleasm.py at line 312: Return code of subprocess was 1['/opt/compleasm_kit/compleasm.py', 'protein', '-p', 'xxx/kp_genome/bbc/genemark.aa', '-l', 'aves_odb10', '-t', '16', '-o', 'xxx/kp_genome/bbc/genemark']
```

I checked for genes >100k in the genemark.aa file and had three:
```
2620_t	179714
2621_t	180497
2618_t	315979
```

As above, I ran compleasm by hand on the genemark.aa file and get the same error messages as above. 

As instructed, I edited the genemark.gtf file (in the GeneMark-ETP folder) by removing the problem genes and removed the genemark.aa file from the bbc folder. I tried to run best_by_compleasm.py again, but the error still persists. Any help greatly appreciated! Let me know if there's anything I can share with you to help :) 

Thank you! 

Josie

**Comment by jolbi** [comment]
Hi @josieparis, I'm not sure about the details of the best_by_compleasm.py script, but when I look in the bbc dir of a successful run, there is a hmmsearch output for each of the predicted transcript sets: GeneMark, Augustus and BRAKER. So it could be that there are additional extra long genes in either Augustus or BRAKER gtf.
You can check this by hand or running hmmsearch on all three .faa files and see if it goes through. The error you posted is indeed a hmmsearch error, so I think there are still some problems with one of your faa files.
Hope this helps.

**Comment by KatharinaHoff** [comment]
I pushed a commit to https://github.com/Gaius-Augustus/TSEBRA/blob/fix_braker_issue_882/bin/best_by_compleasm.py to remove the >100k proteins by GeneMark prior running hmmer in compleasm. I have not tested this because I currently do not have a good test set at hand. If you confirm this solves the problem for you, I can pull it into main and build a new container.

We are independently discussing whether or not to remove these genes from the final output. They may kill pipelines for functional annotation.

**Comment by KatharinaHoff** [comment]
Hold on testing, I think I have to fix sth

**Comment by KatharinaHoff** [comment]
Now it should work. Sorry, I previously forgot that I made getAnnoFastaFromJoinGenes adhere to the 80 characters per line limit in fasta format... so lines have to concatenated, first.

https://github.com/Gaius-Augustus/TSEBRA/blob/fix_braker_issue_882/bin/best_by_compleasm.py

**Comment by josieparis** [comment]
Hi Katharina (and jolbi),

Thanks for your very fast response! I'll try the updated best_by_compleasm.py today and will let you know how it works out. 

Thanks again!

Josie

**Comment by josieparis** [comment]
Hi Katharina, 

It's looking good! Just a directory error:

```
BRAKER is missing 5.59 BUSCOs.
GeneMark is missing 4.43 BUSCOs.
Augustus is missing 1.1 BUSCOs.
All BUSCOs present in augustus.hints.gtf and genemark.gtf will be added to the braker.gtf gene set.
Traceback (most recent call last):
  File "$dir/TSEBRA/bin/best_by_compleasm.py", line 645, in <module>
    main()
  File "$dir/TSEBRA/bin/best_by_compleasm.py", line 557, in main
    keep_aug_dict = parse_hmmsearch_output(hmmoutdir, score_dict, length_dict)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$dir/TSEBRA/bin/best_by_compleasm.py", line 95, in parse_hmmsearch_output
    for hmmsearch_output in os.listdir(hmm_out_dir):
                            ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/new_output/augustus/aves_odb10_hmmsearch_output'
```

Inside `xxx/new_output/augustus/` I have the .out files from the hmmsearch, they're just not parsed to the odb10 directory.

Thanks again!

Josie

**Comment by josieparis** [comment]
Thanks very much yec! I will try your suggestions next week as the cluster I use is currently down for maintenance.

**Comment by josieparis** [comment]
Hi Katharina, all, 

My cluster is up and running again. I tried to pick up where I left off and downloaded the latest version of `best_by_compleasm.py`, which appears to have changed since yec's comment above. 

Now am I getting the same error as before (now on line 339):

```
frameinfo = getframeinfo(currentframe())
```

The error message:
```
Error in file xxx/TSEBRA/bin/best_by_compleasm.py at line 339: Return code of subprocess was 1['xxx/compleasm_kit/compleasm.py', 'download', 'aves']
```
I ran compleasm.py on the genemark.aa file generated in my the new output folder and it runs without error.

Thanks again for your help! As always, let me know if I can help further by sharing any more information.

Josie

**Comment by ice-cold** [comment]
Hi Josie,

There are two solutions: (1) Revise the scripts for compleasm.py (version 0.2.4) and best_by_compleasm.py as previously suggested. (2) Simply update compleasm to version 0.2.6, not the best_by_compleasm.py script which is from TSEBRA, and while I have made some minor revisions related to the BUSCO lineage download, this should not pose significant issues.

If you choose to update to the new version, I recommend starting from the beginning, as many updates may not be compatible with previous versions. You can also use the provided examples for quick testing.

yec

**Comment by josieparis** [comment]
Hi everyone, I had some time to test today and I solved the issue. 

To be clear, the line numbers yec mentioned above refer to the previous version of `best_by_compleasm.py` and I was trying to test Katharina's new commit (posted above). 

The new commit ran well in my previous test and then stopped working after I had the directory error with the error I posted above (line 339). I sourced the problem of this error to a temporary file `file_versions.tsv.tmp` which is written by compleasm during the download stage, meaning that my previous successful run (as above) was then unable to proceed. After removing this file, and updating to compleasm version 0.2.6 the script ran without error. 

Thanks everyone for your help! Katharina, let me know if you would like me to share any of my files for any further testing. 

Josie

**Comment by KatharinaHoff** [comment]
[BRAKER4](https://github.com/Gaius-Augustus/BRAKER4) has built-in quality control: BUSCO, compleasm, OMArk, and optional gffcompare all run as separate Snakemake rules in their own containers. Path and version issues are eliminated.
